//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPAUTOPOWEROFF_H
#define UIMENUWNDSETUPAUTOPOWEROFF_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupAutoPowerOffCtrl;//Panel type 

extern VControl UIMenuWndSetupAutoPowerOff_List_TextCtrl;//List type 

typedef enum
{
UIMenuWndSetupAutoPowerOff_List_Text_STRID_OFF,
UIMenuWndSetupAutoPowerOff_List_Text_MAX
}UIMenuWndSetupAutoPowerOff_List_Text_Setting;

#endif
